services:
  db:
    image: postgres:15
    container_name: speaksmart_db
    environment:
      POSTGRES_USER: speaksmart
      POSTGRES_PASSWORD: speaksmart_secret
      POSTGRES_DB: speaksmart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - speaksmart_net

  adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      networks:
        - speaksmart_net
      depends_on:
        - db

networks:
  speaksmart_net:

volumes:
  postgres_data: