"""initial schema

Revision ID: b557a1db36d2
Revises: 
Create Date: 2026-04-14 21:38:55.956419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b557a1db36d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('average_accuracy', sa.Float(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('active_students', sa.Integer(), nullable=False),
    sa.Column('phoneme_error_breakdown', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instructor_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('exercises',
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('instructor_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('modules',
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exercise_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('student_uid', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['student_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrases',
    sa.Column('phrase_id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('japanese_text', sa.String(), nullable=False),
    sa.Column('romaji', sa.String(), nullable=False),
    sa.Column('english_translation', sa.String(), nullable=False),
    sa.Column('reference_audio_url', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('phrase_id')
    )
    op.create_table('progress_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_uid', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('average_accuracy', sa.Float(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.ForeignKeyConstraint(['student_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('student_uid', sa.String(), nullable=False),
    sa.Column('phrase_id', sa.String(), nullable=False),
    sa.Column('audio_file_url', sa.String(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('mora_timing_score', sa.Float(), nullable=False),
    sa.Column('consonant_score', sa.Float(), nullable=False),
    sa.Column('vowel_score', sa.Float(), nullable=False),
    sa.Column('phoneme_error_map', sa.JSON(), nullable=True),
    sa.Column('feedback_text', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.phrase_id'], ),
    sa.ForeignKeyConstraint(['student_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('exercise_phrases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('phrase_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.phrase_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_phrases')
    op.drop_table('attempts')
    op.drop_table('progress_summary')
    op.drop_table('phrases')
    op.drop_table('exercise_assignments')
    op.drop_table('users')
    op.drop_table('modules')
    op.drop_table('exercises')
    op.drop_table('classes')
    op.drop_table('class_analytics')
    # ### end Alembic commands ###
